// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akjfobymdlyfigyxttuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFramZvYnltZGx5ZmlneXh0dHVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNDM4MjUsImV4cCI6MjA2MjgxOTgyNX0.URV6urmz8aBx4bOrb2Z-0JGqDTKDdgP9uqUqgFUB0XA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);